/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      backgroundColor: ['after', 'before'],
      display: ['after', 'before'],
      height: ['after', 'before'],
      width: ['after', 'before'],
      position: ['after', 'before'],
      bottom: ['after', 'before'],
      left: ['after', 'before'],
      letterSpacing: ['after', 'before'],
      backgroundImage: ['after', 'before'],
      top: ['after', 'before'],

      screens: {
        'tablet': '640px',
        'laptop': '1280px',
        'desktop': '1280px',
        'lg-desktop': '1440px',
      },
      colors: {
        "deep-blue": "#3d5a80",
        "deep-light-blue": "#98c1d9",
        "light-blue": "#e0fbfc",
        "burnt-orange": "#ee6c4d",
        "shale-grey": "#293241",
      },
      margin: {
        '10px': '10px',
        '5px': '5px',
        '13.5px': '13.5px',
        '30px': '30px',
        '70px': '70px',
        '165.5px': '165.5px',
        '0.5625rem': '0.5625rem',
        '0.9375em': '0.9375em',
        'header': '0.84375rem',
      },
      padding: {
        '5px': '5px',
        '10px': '10px',
        '13px': '13px',
        '15px': '15px',
        '20px': '20px',
        '21px': '21px',
        '25px': '25px',
        '30px': '30px',
        '41px': '41px',
        '45px': '45px',
        '60px': '60px',
        '63px': '63px',
        '81px': '81px',
        '150px': '150px',
        '50px': '50px',
      },
      fontSize: {
        'star': '.9375rem',
        xs: '.625rem',
        s: '.75rem',
        sm: '0.8rem',
        base: '1rem',
        xl: '1.25rem',
        '2xl': '1.563rem',
        '3xl': '1.953rem',
        '4xl': '2.441rem',
        '5xl': '3.052rem',
        'smol': '17px',
        'hundred': '5.9375rem',
        'header-bullet': '2.8125rem'
      },
      fontFamily: {
        sans: ['Avenir', 'Helvetica', 'Arial', 'sans-serif'],
        AvenirNext: ['AvenirNext', 'Helvetica', 'Arial', 'sans-serif'],
        AvenirNextLight: ['AvenirNextLight', 'AvenirNext', 'Helvetica', 'Arial', 'sans-serif'],
        times: ['Times']
      },
      width: {
        'unset': 'unset',
        '1px': '1px',
        '90px': '90px',
      },
      height: {
        '90%': '90%',
        '90px': '90px',
      },
      lineHeight: {
        'star': '1.3125rem',
        'review-number': '1.375rem',
      },
      borderWidth: {
        '1px': '1px',
        '5px': '5px',
      },
      spacing: {
        'neg-1px': '-1px',
        'neg-30px': '-30px',
        'neg-24px': '-24px',
        'neg-15': '-15px',
        '19px': '-19px',
        '4px': '4px',
        '5px': '5px',
        '10px': '10px',
        '15px': '15px',
        '30px': '30px',
        '50px': '50px',
        '108px': '108px',
        '113px': '113px',
        '280px': '280px',
        '292px': '292px',
        '300px': '300px',
        '346px': '346px',
        '384px': '384px',
        '424px': '424px',
        '576px': '576px',
        '588px': '588px',
        '5%': '5%'
      },
      letterSpacing: {
        wider: '.08em',
        '3px': '3px',
        '.048px': '.048px',
      },
      borderRadius: {
        'profile': '50%',
      },
      translate: {
        '2px': '2px',
        '-7px': '-7px',
      },
      backgroundImage: {
        'border-gradient': 'linear-gradient(135deg, #f8f8f8 0%, #fff 98.8%)',
        'custom-gradient': 'linear-gradient(180deg, #3d5a80 70%, #3d6080)',
        'picture-gradient': 'linear-gradient(180deg, #3d5a80 70%, #3d6080)',
        'border-gradient': 'linear-gradient(to right, #3d5a80, hsla(0, 0%, 100%, 0))',
        'read-more-gradient': 'radial-gradient(hsla(0, 0%, 100%, 0) 90%, #3d5a80)',
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
    },
  },
  plugins: [],
};
